# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  thesaucerecipes.com:
    site_hosts:
      - thesaucerecipes.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:isabisa/the-sauce-recipes.git
    branch: master
    subtree_path: site # relative path to your Bedrock/WP directory in your repo (above) if it is not the root (like the roots-example-project structure)
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://thesaucerecipes.com
      wp_siteurl: http://thesaucerecipes.com/wp
      wp_env: production
      db_name: sauce_prod
      db_user: sauce_dbuser
      db_password: Noj(lEd/gIj)peB$K
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      # These CANNOT contain the characters "{%" in succession
      auth_key: "2/Gag00-cXSK;Zwmu)tZI$G_.*yMIylZOH+{Q)_f<G`y66O1@-I<dNx]7O]^Y5/)"
      secure_auth_key: "n4j)JgBshmTag>nG-y[R+0rK8b#;~zuhdLs;|hfVI8{1/;2t<w@pNrP!kEcY=/d!"
      logged_in_key: "7BP_gk5D:LJV98`xnT=su9w2DqJ mAwA{qy[l8S6?8n6yY.bh}*)jB{|Aa1Bz5XC"
      nonce_key: "iy|+W62>W3&%$]wPuEgEKeQv,]?g&?@}lk1Cro#nLX|:$^prROc!-ra4t;siU&*&"
      auth_salt: "Pg!&q.H4Irz>^WmlR=NMxye5QQ;]1~{Ew&Xd}mF58&f$_(I|K*fj`}53rcZ+2+*:"
      secure_auth_salt: "$oT{-{OQa,4wp1x<FCl&S,IM0U_zn/]q$7DI:)VDf[b$%xM~e=c9bvCQCu.#*evi"
      logged_in_salt: "_G3&]B+ymg}6vn54cLixyZ8iaz2g73:-a>YP(xnyk)I?o#&T;(7b,&@u~!*FT~/7"
      nonce_salt: "2Z0: d(2j$ovM%T#L3{i*Kp;-_pjAyCau(DDvC;s#c(&h^qRr/EW-clYm*G-F,|I"
